name: Actions - lint, test, build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm i

      - name: Build project (PROD)
        run: npm run build:prod

      - name: Lintings typescript
        run: npm run lint:ts

      - name: Lintings stylesheet
        run: npm run lint:scss

      - name: Unit testings
        run: npm run test:unit

      - name: Lintings stylesheet
        run: npm run lint:scss